// <auto-generated />
using System;
using CitiesManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623081028_CreatCities")]
    partial class CreatCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.API.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("52f39431-de72-411b-ac43-64b55ff766a1"),
                            Name = "Dhaka"
                        },
                        new
                        {
                            CityID = new Guid("873bcf7e-d454-4272-923a-8124abda6ba2"),
                            Name = "Mymenshingh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
